### ISSUE TITLE
Miscellaneous Suggestions

### ISSUE THREAD

**Issue by Jayonas** [Rhodney/keepass-icons#1]
Hey, these icons are really great, thanks for making them!

A few additional suggestions:
* Backerkit -- https://www.backerkit.com/brand_assets
* Bandcamp -- https://bandcamp.com/buttons
* BoardGameGeek -- https://boardgamegeek.com (can't find a branding page, but the logo is in the usual top left)
* Discord -- https://discord.com/branding
* Gamefound -- https://help.gamefound.com/article/129-media-kit-for-promotion
* Kickstarter -- https://www.kickstarter.com/help/brand_assets?ref=press_brand
* Western Digital -- https://www.westerndigital.com/legal/trademarks (this page references the "Western Digital Brand Guidelines", but I can't actually find them anywhere; their various logos are at the top of their web site footer, though)

These ones unfortunately don't seem to have square-ish image logos, just words which probably won't icon-ize very well, but I figured I'd toss them out there anyway in case anything decent can still be done with them:
* Netgear -- https://pressroom.netgear.com/branding/all
* Synology -- https://www.synology.com/en-ca/company/branding

More general ideas:
* Large well-known banks.
* Country flags (e.g. for government-related entries)

Now I just wish I could find a similarly optimized pack of icons for a wider variety of general categories like health, transportation, financial, education/school, entertainment, shopping, etc.  Most of the built-in ones are so technical, and the one additional pack on the KeePass web site isn't much help.

**Comment by Rhodney** [comment]
Hello friend.
I added at least 1 icon of each link you suggested, so you can use it now.

For logos that have multiple versions, such as Discord, for now I have only entered the main version. I'm still thinking about how to handle different versions of the same company's logos, like in light or dark themes.

I also intend to insert icons from large banks in subfolders, but as there are many, this may take a while. If you are in a hurry or have a preference for a particular bank or category, please let me know so I can start with it.

I will insert at least the most useful ones from the official emoji collection, which includes flags of almost every country and various markers.

**Comment by Jayonas** [comment]
Thanks again, these are great!  I look forward to the flags and other misc markers, but the large banks actually aren't very helpful for me personally so I'll leave it to others to make specific suggestions there.
