### ISSUE TITLE
Bunch of recommendations

### ISSUE THREAD

**Issue by bjsvedin** [Rhodney/keepass-icons#3]
I have a bunch of recommendations for services and software I frequently use but did not have here.

AWS (Yes you have Amazon, but their cloud services are very different)
Figma
HubSpot
Imgur
JetBrains
MongoDB
NewEgg
NPM
Pandora
Plex
Sentry
Slack
Venmo
A good WIFI symbol

I quickly created most of these for myself, but thought i would also add them as recommendations here.

**Comment by Rhodney** [comment]
Thanks for the suggestion. I'll work on them this week and will probably upload them tomorrow, along with some others that are already done.

**Comment by bjsvedin** [comment]
These icons are great!! Thanks for adding them in. 

Turns out I messed up and wasn't more explicit with what I meant by "Sentry". You used the Sentry Insurance logo, but I was referring to the sentry.io application monitoring software. I was rather tunnel visioned with that one and didn't think it was a rather vague name.

Thanks again.

**Comment by Rhodney** [comment]
Don't worry. I've added the sentry.io icon.

Thanks for the suggestions.
